version: '3.8'

services:
  database:
    image: mongo:latest
    container_name: mongo-db
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - mongodata:/data/db
    networks:
      - app-network
      
  client:
    build: ./client
    container_name: react-ui
    depends_on:
      - backend
    ports:
      - "3000:3000"
    networks:
      - app-network
    stdin_open: true
    tty: true
    
  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: node-api
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - database
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodata: